### ISSUE TITLE
does not work with vrp?

### ISSUE THREAD

**Issue by hartturmch** [PichotM/VoiceChat#1]
how i can make it work with vrp?

**Comment by Sytrookie** [comment]
You will probably need to disable vrp implementation to control voice ranges.

**Comment by hartturmch** [comment]
yeah thats true, i did that and it worked

**Comment by hartturmch** [comment]
but when i did this, everyone is listening everyone everywhere
in the hospital im listening guys in the dp

**Comment by PichotM** [comment]
Hello, fixed by this commit https://github.com/PichotM/VoiceChat/commit/b371c31257ec8eb3036d0432a04b9147516b9852
