### ISSUE TITLE
get random global chat

### ISSUE THREAD

**Issue by DrPeluche** [PichotM/VoiceChat#2]
since friday's update (fivem) some players can hear others as if they were chatting across the map.
it appears to be random atm.

No new ressources implemented, nor server updates

_______________________

Hello, du coup depuis vendredi soir certaines personnes entendent d autres joueurs comme si ils étaient en chat global ( et oui il y a plusieurs km entre les deux joueurs). Ce souci arrive de manière totalement random.

Auncune nouvelle ressources ajoutée, ni d update serveur.

**Comment by PERPGamer** [comment]
Try the patch he has done, it should fix this issue

**Comment by PichotM** [comment]
https://github.com/PichotM/VoiceChat/commit/b371c31257ec8eb3036d0432a04b9147516b9852
